[package]
name = "expo_push_server_example"
version = "0.1.0"
authors = ["Brent Vatne <brentvatne@gmail.com>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
reqwest = "0.7.1"